const villagers = [
  {
    id: 12,
    "file-name": "bea05",
    name: {
      "name-USen": "Nate",
      "name-EUen": "Nate",
      "name-EUde": "Nathan",
      "name-EUes": "Nachete",
      "name-USes": "Nachete",
      "name-EUfr": "Nathan",
      "name-USfr": "Nathan",
      "name-EUit": "Gianni",
      "name-EUnl": "Nate",
      "name-CNzh": "巴克思",
      "name-TWzh": "巴克思",
      "name-JPja": "バッカス",
      "name-KRko": "박하스",
      "name-EUru": "Нэйт",
    },
    personality: "Lazy",
    "birthday-string": "August 16th",
    birthday: "16/8",
    species: "Bear",
    gender: "Male",
    subtype: "B",
    hobby: "Play",
    "catch-phrase": "yawwwn",
    icon_uri: "https://acnhapi.com/v1/icons/villagers/12",
    image_uri: "https://acnhapi.com/v1/images/villagers/12",
    "bubble-color": "#e8b010",
    "text-color": "#fffce9",
    saying: "Be true to yourself.",
    "catch-translations": {
      "catch-USen": "yawwwn",
      "catch-EUen": "yawwwn",
      "catch-EUde": "gäähn",
      "catch-EUes": "uuaaaah",
      "catch-USes": "uuaaaah",
      "catch-EUfr": "baaîîîllle",
      "catch-USfr": "baaîîîllle",
      "catch-EUit": "yauuun",
      "catch-EUnl": "gaaaap",
      "catch-CNzh": "嗯是",
      "catch-TWzh": "嗯是",
      "catch-JPja": "んだ",
      "catch-KRko": "힘내",
      "catch-EUru": "спа-а-ать",
    },
  },
  {
    id: 200,
    "file-name": "hip03",
    name: {
      "name-USen": "Bertha",
      "name-EUen": "Bertha",
      "name-EUde": "Berta",
      "name-EUes": "Berta",
      "name-USes": "Berta",
      "name-EUfr": "Bertha",
      "name-USfr": "Bertha",
      "name-EUit": "Umberta",
      "name-EUnl": "Bertha",
      "name-CNzh": "豆沙",
      "name-TWzh": "豆沙",
      "name-JPja": "あんこ",
      "name-KRko": "베티",
      "name-EUru": "Берта",
    },
    personality: "Normal",
    "birthday-string": "April 25th",
    birthday: "25/4",
    species: "Hippo",
    gender: "Female",
    subtype: "B",
    hobby: "Education",
    "catch-phrase": "bloop",
    icon_uri: "https://acnhapi.com/v1/icons/villagers/200",
    image_uri: "https://acnhapi.com/v1/images/villagers/200",
    "bubble-color": "#00d1bd",
    "text-color": "#fffce9",
    saying: "The best part of spring is the picnics!",
    "catch-translations": {
      "catch-USen": "bloop",
      "catch-EUen": "bloop",
      "catch-EUde": "saug",
      "catch-EUes": "churubú",
      "catch-USes": "churubú",
      "catch-EUfr": "sploush",
      "catch-USfr": "sploush",
      "catch-EUit": "blub",
      "catch-EUnl": "bloep",
      "catch-CNzh": "认同",
      "catch-TWzh": "認同",
      "catch-JPja": "せやねん",
      "catch-KRko": "약히",
      "catch-EUru": "буль",
    },
  },
  {
    id: 200,
    "file-name": "hip03",
    name: {
      "name-USen": "Bertha",
      "name-EUen": "Bertha",
      "name-EUde": "Berta",
      "name-EUes": "Berta",
      "name-USes": "Berta",
      "name-EUfr": "Bertha",
      "name-USfr": "Bertha",
      "name-EUit": "Umberta",
      "name-EUnl": "Bertha",
      "name-CNzh": "豆沙",
      "name-TWzh": "豆沙",
      "name-JPja": "あんこ",
      "name-KRko": "베티",
      "name-EUru": "Берта",
    },
    personality: "Normal",
    "birthday-string": "April 25th",
    birthday: "25/4",
    species: "Hippo",
    gender: "Female",
    subtype: "B",
    hobby: "Education",
    "catch-phrase": "bloop",
    icon_uri: "https://acnhapi.com/v1/icons/villagers/200",
    image_uri: "https://acnhapi.com/v1/images/villagers/200",
    "bubble-color": "#00d1bd",
    "text-color": "#fffce9",
    saying: "The best part of spring is the picnics!",
    "catch-translations": {
      "catch-USen": "bloop",
      "catch-EUen": "bloop",
      "catch-EUde": "saug",
      "catch-EUes": "churubú",
      "catch-USes": "churubú",
      "catch-EUfr": "sploush",
      "catch-USfr": "sploush",
      "catch-EUit": "blub",
      "catch-EUnl": "bloep",
      "catch-CNzh": "认同",
      "catch-TWzh": "認同",
      "catch-JPja": "せやねん",
      "catch-KRko": "약히",
      "catch-EUru": "буль",
    },
  },
  {
    id: 20,
    "file-name": "bea13",
    name: {
      "name-USen": "Beardo",
      "name-EUen": "Beardo",
      "name-EUde": "Berthold",
      "name-EUes": "Bernabé",
      "name-USes": "Bernabé",
      "name-EUfr": "Eustache",
      "name-USfr": "Eustache",
      "name-EUit": "Barnaba",
      "name-EUnl": "Beardo",
      "name-CNzh": "熊大叔",
      "name-TWzh": "熊大叔",
      "name-JPja": "ベアード",
      "name-KRko": "베어드",
      "name-EUru": "Беардо",
    },
    personality: "Smug",
    "birthday-string": "September 27th",
    birthday: "27/9",
    species: "Bear",
    gender: "Male",
    subtype: "A",
    hobby: "Education",
    "catch-phrase": "whiskers",
    icon_uri: "https://acnhapi.com/v1/icons/villagers/20",
    image_uri: "https://acnhapi.com/v1/images/villagers/20",
    "bubble-color": "#3fd8e0",
    "text-color": "#fffce9",
    saying: "Fashion first!",
    "catch-translations": {
      "catch-USen": "whiskers",
      "catch-EUen": "whiskers",
      "catch-EUde": "brrroho",
      "catch-EUes": "bigotre",
      "catch-USes": "bigotre",
      "catch-EUfr": "poilodos",
      "catch-USfr": "ciao",
      "catch-EUit": "andale",
      "catch-EUnl": "snorhaar",
      "catch-CNzh": "咳咳",
      "catch-TWzh": "咳咳",
      "catch-JPja": "オッホン",
      "catch-KRko": "오홍홍",
      "catch-EUru": "усы мои",
    },
  },
  {
    id: 3,
    "file-name": "ant02",
    name: {
      "name-USen": "Pango",
      "name-EUen": "Pango",
      "name-EUde": "Mathilda",
      "name-EUes": "Aspidora",
      "name-USes": "Aspidora",
      "name-EUfr": "Mathilda",
      "name-USfr": "Mathilda",
      "name-EUit": "Carlotta",
      "name-EUnl": "Pango",
      "name-CNzh": "佩希",
      "name-TWzh": "佩希",
      "name-JPja": "パトラ",
      "name-KRko": "패트라",
      "name-EUru": "Панго",
    },
    personality: "Peppy",
    "birthday-string": "November 9th",
    birthday: "9/11",
    species: "Anteater",
    gender: "Female",
    subtype: "B",
    hobby: "Fashion",
    "catch-phrase": "snooooof",
    icon_uri: "https://acnhapi.com/v1/icons/villagers/3",
    image_uri: "https://acnhapi.com/v1/images/villagers/3",
    "bubble-color": "#00d1bd",
    "text-color": "#fffce9",
    saying: "A thing of beauty is a joy forever.",
    "catch-translations": {
      "catch-USen": "snooooof",
      "catch-EUen": "snooooof",
      "catch-EUde": "schnieef",
      "catch-EUes": "snuf-snuf",
      "catch-USes": "snuf-snuf",
      "catch-EUfr": "pouuuuuf",
      "catch-USfr": "pouuuuuf",
      "catch-EUit": "snuuf",
      "catch-EUnl": "snufffff",
      "catch-CNzh": "希希",
      "catch-TWzh": "希希",
      "catch-JPja": "だっしー",
      "catch-KRko": "라지요",
      "catch-EUru": "снуф-снуф",
    },
  },
  {
    id: 100,
    "file-name": "crd08",
    name: {
      "name-USen": "Drago",
      "name-EUen": "Drago",
      "name-EUde": "Frederik",
      "name-EUes": "Dragonio",
      "name-USes": "Dragonio",
      "name-EUfr": "Drago",
      "name-USfr": "Drago",
      "name-EUit": "Dragonio",
      "name-EUnl": "Drago",
      "name-CNzh": "阿龙",
      "name-TWzh": "阿龍",
      "name-JPja": "タツオ",
      "name-KRko": "용남이",
      "name-EUru": "Драго",
    },
    personality: "Lazy",
    "birthday-string": "February 12th",
    birthday: "12/2",
    species: "Alligator",
    gender: "Male",
    subtype: "A",
    hobby: "Nature",
    "catch-phrase": "burrrn",
    icon_uri: "https://acnhapi.com/v1/icons/villagers/100",
    image_uri: "https://acnhapi.com/v1/images/villagers/100",
    "bubble-color": "#78dd62",
    "text-color": "#28665a",
    saying: "There is no room for two dragons in one pond.",
    "catch-translations": {
      "catch-USen": "burrrn",
      "catch-EUen": "burrrn",
      "catch-EUde": "hömpf",
      "catch-EUes": "quemarrr",
      "catch-USes": "ñami",
      "catch-EUfr": "ducroc",
      "catch-USfr": "ducroc",
      "catch-EUit": "tic tac",
      "catch-EUnl": "puf",
      "catch-CNzh": "然后",
      "catch-TWzh": "然後",
      "catch-JPja": "えーと",
      "catch-KRko": "띠용띠용",
      "catch-EUru": "огонь",
    },
  },
  {
    id: 300,
    "file-name": "pgn13",
    name: {
      "name-USen": "Flo",
      "name-EUen": "Flo",
      "name-EUde": "Susanne",
      "name-EUes": "Nieves",
      "name-USes": "Nieves",
      "name-EUfr": "Nora",
      "name-USfr": "Nora",
      "name-EUit": "Nives",
      "name-EUnl": "Flo",
      "name-CNzh": "蕾拉",
      "name-TWzh": "蕾拉",
      "name-JPja": "レイラ",
      "name-KRko": "레이라",
      "name-EUru": "Фло",
    },
    personality: "Uchi",
    "birthday-string": "September 2nd",
    birthday: "2/9",
    species: "Penguin",
    gender: "Female",
    subtype: "A",
    hobby: "Music",
    "catch-phrase": "cha",
    icon_uri: "https://acnhapi.com/v1/icons/villagers/300",
    image_uri: "https://acnhapi.com/v1/images/villagers/300",
    "bubble-color": "#6b75ce",
    "text-color": "#9ae8df",
    saying: "Always keep a straight face.",
    "catch-translations": {
      "catch-USen": "cha",
      "catch-EUen": "cha",
      "catch-EUde": "flatsch",
      "catch-EUes": "fresqui",
      "catch-USes": "fresqui",
      "catch-EUfr": "golri",
      "catch-USfr": "frigogo",
      "catch-EUit": "iglù",
      "catch-EUnl": "duh",
      "catch-CNzh": "这样唷",
      "catch-TWzh": "這樣唷",
      "catch-JPja": "じゃんよ",
      "catch-KRko": "맞잖아",
      "catch-EUru": "чхи",
    },
  },
];

console.log(`We have ${villagers.length} villagers!`);
